services:
  federation:
    build: .
    restart: unless-stopped
    environment:
      - API_URL=https://snowside.network/v1
      - FEDERATION_TOKEN=${FEDERATION_TOKEN}
      - EWOQ_PRIVATE_KEY=${EWOQ_PRIVATE_KEY}
      - MAINNET_RPC=https://rpc.snowside.network/mainnet
      - TESTNET_RPC=https://rpc.snowside.network/testnet
      - SIGNET_RPC=https://rpc.snowside.network/signet
      - ESPLORA_URL=https://esplora.drynet4.drivechain.dev
      - POLL_MS=10000
